#!/usr/bin/env zsh
# Author:  Maddison Hellstrom <github.com/b0o>
# Repo:    https://github.com/b0o/zsh-extras
# License: MIT

# nvim help
function nvim-help() {
  command nvim -c ":h $1 | on${2:+$(printf ' | tab h %s' "${@:2}")}"
}
