#!/usr/bin/env zsh
# Author:  Maddison Hellstrom <github.com/b0o>
# Repo:    https://github.com/b0o/zsh-extras
# License: MIT

function pacopen() {
  local url="$(pacman -Si "$1" | awk '/^URL/{print $3}')"
  echo "$1 $url" >&2
  xdg-open "$url" > /dev/null 2>&1
}
