#!/usr/bin/env zsh
# Author:  Maddison Hellstrom <github.com/b0o>
# Repo:    https://github.com/b0o/zsh-extras
# License: MIT

# usage: pqlmg pat package [package ..]
# search manual pages owned by package for pat
# depends on MANPATH
function pqlmg() {
  [[ $# -gt 1 ]] || return 1
  local pat="$1"
  shift
  pqlm -p "$@" | mg "$pat"
}
