#!/usr/bin/env zsh
# Author:  Maddison Hellstrom <github.com/b0o>
# Repo:    https://github.com/b0o/zsh-extras
# License: MIT

# query package that owns a given command
function pqoc() {
  local p c
  for c in "$@"; do
    p="$(command -v "$c")" || {
      echo "error: not found in path: $c" >&2
      return 1
    }
    pacman -Qo "$p"
  done
}

# compdef pqoc=command
